# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Heroku deployment
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          server-id: docker.io
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

          - name: Building and Pushing demo-service
            run: mvn package dockerfile:push --file demo/pom.xml
            env:
              MAVEN_USERNAME: ${{ secrets.DOCKER_USERNAME }}
              MAVEN_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    - name: Heroku Action
  # You may pin to the exact commit or the version.
  # uses: CDNievas/heroku-action@c9cf9c85571e67583e44ec92c0d1113f66b0e838
      uses: techmmunity/docker-heroku-deploy@v1.0.0
      with:
        heroku_api_key: ${{secrets.HEROKU_KEY}}
        heroku_email: ${{secrets.HEROKU_EMAILID}} 
        heroku_app_name: ${{secrets.HEROKU_APPNAME}}
 
